### PR TITLE
Added R Collective

### PR DESCRIPTION
**Pull request by MdoubleDash**
Added [R Collective chat room](https://chat.stackoverflow.com/rooms/252171/r-language-collective);

### CODE REVIEW

**Comment by MdoubleDash** [comment]
I am in the process of getting ROs approval for this. I will post a comment with a link to chat when I get that.

**Comment by MdoubleDash** [comment]
ROs approval for adding Natty to the room: https://chat.stackoverflow.com/transcript/message/56624811#56624811 cc: @Bhargav-Rao

**Comment by Bhargav-Rao** [comment]
Looks nice overall. You'd need to change [RunNewNatty.java#L35](https://github.com/SOBotics/Natty/blob/master/src/main/java/in/bhargavrao/stackoverflow/natty/clients/RunNewNatty.java#L35) to RCollective Room. (R Public is now frozen, so no need to post there)

**Comment by MdoubleDash** [comment]
> Looks nice overall. You'd need to change [RunNewNatty.java#L35](https://github.com/SOBotics/Natty/blob/master/src/main/java/in/bhargavrao/stackoverflow/natty/clients/RunNewNatty.java#L35) to RCollective Room. (R Public is now frozen, so no need to post there)

Done!

**Pull request merged**
